### ISSUE TITLE
How to translate this documentation?

### ISSUE THREAD

**Issue by simon511000** [SleekDB/sleekdb.github.io#1]
I would like to translate this documentation into French, how can I do it?

**Comment by rakibtg** [comment]
@simon511000 I am sorry that I haven't seen your ticket yet! That would be really great! I am in a process of re-writing the homepage with few updates regarding API changes in the doc. It would be great if you are still interested so i can keep you updated when new site is done.

**Comment by simon511000** [comment]
Oh yes I'm still interested, thank you very much ;)

**Comment by rakibtg** [comment]
Thanks!
