### ISSUE TITLE
Menu click issue

### ISSUE THREAD

**Issue by rakibtg** [SleekDB/sleekdb.github.io#3]
After clicking on a menu, it will not scroll-up the content automatically. It should scroll top.

**Comment by Timu57** [comment]
https://github.com/SleekDB/sleekdb.github.io/blob/5da6b9371eafc8d236755a56445ebe6f9bfa9517/assets/app.js#L54

https://stackoverflow.com/questions/1174863/javascript-scrollto-method-does-nothing
