### ISSUE TITLE
Whole page is shown

### ISSUE THREAD

**Issue by Timu57** [SleekDB/sleekdb.github.io#5]
When visiting the homepage (not using the menu) the whole html document is shown, not just the home part.

**Comment by rakibtg** [comment]
@Timu57 At the beginning I have done this intentionally as the documentation was not that long as well as it helped SEO purposes. I have plan to move to a better documentation site after this release.

**Comment by Timu57** [comment]
If that is intentionally its ok, thought its a bug :smile:
